### PR TITLE
|Pages||Timelogs| Update usernames with full name

### PR DESCRIPTION
**Pull request by jkrobicki**
In timelogs page the selector and table component username will now display dyvenia username fetched from dyvenia email
- closes a task in https://github.com/dyvenia/timeflow/issues/372
- 
image

### CODE REVIEW

**Comment by acivitillo** [comment]
can you add screenshots like @zuzka98 does?

**Comment by jkrobicki** [comment]
@acivitillo sure, done

**Comment by acivitillo** [comment]
I think you should use the user name and lastname which we mantain in timeflow, why using the email address?

**Comment by jkrobicki** [comment]
@acivitillo Good point, is that better? `last_name + first_name`

image

**Comment by acivitillo** [comment]
yes, did you update all the code?

**Comment by jkrobicki** [comment]
no, I'll let you know when it's ready to merge

**Comment by jkrobicki** [comment]
@acivitillo  ok, this one's ready to merge

**Pull request merged**
