### PR TITLE
modified pagination

### PR DESCRIPTION
**Pull request by DaniilJSN**

### CODE REVIEW

**Comment by liberty-rising** [comment]
Seems to work flawlessly. I think it'd be a good idea to have the "per page" dropdown display "Results per page:" instead of "2". Also can you change it to 5, 10, 15 instead of 2, 4, 6? Default would be 5.

**Comment by DaniilJSN** [comment]
> Seems to work flawlessly. I think it'd be a good idea to have the "per page" dropdown display "Results per page:" instead of "2". Also can you change it to 5, 10, 15 instead of 2, 4, 6? Default would be 5.

I’ve updated the 3 mentioned points

**Review by liberty-rising — APPROVED** [review]

**Comment by liberty-rising** [comment]
Closes #130

**Review by jkrobicki — APPROVED** [review]

**Comment by acivitillo** [comment]
are we going to continue to add components here or move this repo to `uiflow` lib?

**Comment by liberty-rising** [comment]
@acivitillo Once it's packaged then we can start adding them to `uiflow`. Need to have `timeflow_ui` renamed before packaging it.

**Comment by acivitillo** [comment]
ok, should we then do the other way around? We can ask @DaniilJSN to update the `timeflow` components to match the ones in `timeflow_ui`. Once that is done, we can carve out the lib `uiflow` from `timeflow`

**Comment by liberty-rising** [comment]
@acivitillo Sounds good, I didn't realize that there are updated components in `timeflow_ui` that aren't in `timeflow`.

**Comment by acivitillo** [comment]
yes there are, if `uiflow` is not priority, I suggest we merge `timeflow_ui` into timeflow so @DaniilJSN can work out of 1 repo only

**Pull request merged**
