### PR TITLE
Create [data] folder for storing common data

### LINKED ISSUE #129: Create [data] folder for storing common data
- [x] add `data` folder
- [x] add `common.py` file for common data
- [x] add `<page>.py` file for each page storing call methods for each page api data

### PR DESCRIPTION
**Pull request by liberty-rising**
Added data folder
Added data.py file for common data
Added <page>.py file for each page storing call methods for each page api data
Renamed data.py to common.py and updated paths

_Newer pages such as epic_areas, teams, and sponsors still need to be refactored into their corresponding data files. Will create an issue for this shortly._

Closes #129

### CODE REVIEW

**Comment by liberty-rising** [comment]
Hold on, don't merge yet. Something broke in the app. Working on the fix.

**Comment by liberty-rising** [comment]
Issue fixed. Ready for merge.

**Comment by acivitillo** [comment]
I wonder if we want `/data` to be in `/pages`, shouldn't it be in `/frontend`?

**Comment by liberty-rising** [comment]
It does bloat up the import so perhaps it'd make things cleaner. I put it in `/pages` because all of the contained code is so far only concerned with the frontend pages. However I could see it being used in other frontend areas. I'll change it now.

**Comment by liberty-rising** [comment]
Everything looks to be working. Let me know if there's anything else.

**Pull request merged**
